### ISSUE TITLE
Stack was not created.

### ISSUE THREAD

**Issue by mcartagenah** [spotty-cloud/spotty#101]
Hello,

After using spotty start it says:

```
Error:
------
Stack "spotty-my-project-1" was not created.
Please, see CloudFormation logs for the details.

```
But in CloudFormation in Stacks there's nothing about the stack.

I have a local instance that works perfectly, so I'm assuming is not a problem with the Dockerfile.

**Comment by apls777** [comment]
Are you sure you don't have any info about the stack? Please, check that you're in the right region in the AWS console.

**Comment by mcartagenah** [comment]
You're right, I was in the wrong region, sorry about that. I get this error:
```
Max spot instance count exceeded (Service: AmazonEC2; Status Code: 400; Error Code: MaxSpotInstanceCountExceeded; Request ID: 6d512814-7adb-433d-84c6-c91dfab2e69c; Proxy: null)
```

**Comment by apls777** [comment]
You need to increase your Spot Instance limit. Check out this page: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-limits.html.
