### ISSUE TITLE
Select GCP disk type

### ISSUE THREAD

**Issue by turian** [spotty-cloud/spotty#105]
There are a handful of [GCP disk types](https://cloud.google.com/compute/docs/disks). How can I change the disk type?

I very much want to add `pd-ssd` disks, and perhaps `pd-extreme`, persistent disk.

It would also be nice to add local SSDs from spotty.

Related #45

**Comment by apls777** [comment]
Selecting disk types and adding local SSDs is not supported for GCP at the moment.

For disk types, there is a workaround: you can just pre-create a disk with the desired type before launching an instance with Spotty, then Spotty will pick it up instead of creating a new one.

**Comment by turian** [comment]
@apls777 for the workaround, do I have to give the disk I create a particular name (the name of the disk it would otherwise create)? Anything else necessary for this workaround?

**Comment by turian** [comment]
@apls777  Also, does this workaround work for attaching local SSDs? If not, is there any way?

**Comment by apls777** [comment]
@turian Sorry for the delay in getting back to you. 

> for the workaround, do I have to give the disk I create a particular name (the name of the disk it would otherwise create)? 

Yes, it should be in the format `<project_name>-<instance_name>-<volume_name>`, all lowercase. For example: `hearpreprocess-hearpreprocess-i1-joseph-workspace` (using your config from another issue).

> Anything else necessary for this workaround?

I don't think so.

> Also, does this workaround work for attaching local SSDs? If not, is there any way?

No, unfortunately, it won't work for SSDs. There is no simple workaround, it requires editing the deployment template in the Spotty code.

**Comment by turian** [comment]
Thank you!
