### ISSUE TITLE
Caught non-retryable exception while listing file:///mnt/heareval-heareval-leader-joseph-workspace/project: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by turian** [spotty-cloud/spotty#110]
I ran into root disk space problems, and then my docker terminated. `spotty sh` complained there was not enough space in /tmp, and would not run.

I removed `/opt/conda/` by SSH'ing directly into the machine. I also used the cloud console to add 50GB more to the root volume.

Now, I think I have enough disk space on the machine:
```
Filesystem      Size  Used Avail Use% Mounted on
udev            103G     0  103G   0% /dev
tmpfs            21G  8.5M   21G   1% /run
/dev/sda1        99G   45G   50G  48% /
tmpfs           103G     0  103G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           103G     0  103G   0% /sys/fs/cgroup
/dev/sda15      124M  5.7M  119M   5% /boot/efi
/dev/sdb        2.0T  833G  1.2T  43% /home/jupyter
tmpfs            21G     0   21G   0% /run/user/1004
tmpfs            21G     0   21G   0% /run/user/1003
```

However, `spotty sh` is broken, and I have the following error in my `/var/log/startup-script.log`:
```
Caught non-retryable exception while listing file:///mnt/heareval-heareval-leader-joseph-workspace/project: [Errno 28] No space left on device
```

Why don't I have enough space on the device? How can I spotty into the machine again?

**Comment by apls777** [comment]
Is it still an issue for you? Can you share your `spotty.yaml`?

**Comment by turian** [comment]
This seems to have resolved, thank you
