### ISSUE TITLE
Question: Possibility to execute code on instance startup 

### ISSUE THREAD

**Issue by hjander** [spotty-cloud/spotty#111]
I have an ami that does not comply with python >= 3.6 requirement and would like to fix that on instance startup via script.

Is that doable right now ?

Creating an own ami is not an option.

**Comment by apls777** [comment]
There is no requirement for AMI to support Python 3.6. As long as it's Ubuntu with NVIDIA Docker installed, it will work. Or do you mean Python in your Docker image? Then it doesn't matter as it will run inside a container.
