### ISSUE TITLE
What's the reason for nitro instance types not being supported? Specifically I'd like to use the p3dn.24xlarge instance type

### ISSUE THREAD

**Issue by nickwalton** [spotty-cloud/spotty#64]

**Comment by apls777** [comment]
Nitro-based instances have different device names for attached EBS volumes (see [Amazon EBS and NVMe on Linux Instances](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/nvme-ebs-volumes.html)). Moreover, they say: 
> The block device driver can assign NVMe device names in a different order than you specified for the volumes in the block device mapping.

That means, it should be a smarter way to figure out which volume is which.

At the moment, a Nitro-based instance would fail to start if you attached any volume. So, for now, I decided to disable this functionality at all.

**Comment by apls777** [comment]
Now Spotty supports Nitro-based instances.
