### ISSUE TITLE
Docker with private dockerhub or gitlab image?

### ISSUE THREAD

**Issue by turian** [spotty-cloud/spotty#79]
If I have a private dockerhub or gitlab docker image, how do I authenticate with these services in Spotty to pull my docker instance?

**Comment by apls777** [comment]
@turian You can use the `commands` parameter in the instance configuration (see [here](https://spotty.cloud/docs/providers/aws/instance-parameters.html)). These commands will be executed before the Docker image is built or pulled. For example, in [this article](https://towardsdatascience.com/run-deep-learning-containers-on-aws-with-one-command-114898e1eb5), I showed how to do it for AWS ECR.

**Comment by turian** [comment]
Thank you.
