### ISSUE TITLE
Deprecated link to specification file in README

### ISSUE THREAD

**Issue by wilmeragsgh** [spotty-cloud/spotty#87]
Hi Everybody, thanks so much for such an amazing projects was starting to play around with and noticed that the link for the configuration file is deprecated:

I suppose that the link should be https://spotty.cloud/docs/user-guide/configuration-file.html , right?

Currently it points to: https://spotty.cloud/docs/configuration-file/

Thanks again!

**Comment by apls777** [comment]
That's right, thank you!
