### ISSUE TITLE
Why starts on-Demand instance?

### ISSUE THREAD

**Issue by PapoKarlo** [spotty-cloud/spotty#89]
Hi, i try this config

`project:
  name: aws-project
  syncFilters:
    - exclude:
        - .git/*
        - .idea/*
        - .*
        - '*/__pycache__/*'

containers:
  - projectDir: /home/jr/aws_spot
    image: tensorflow/tensorflow:nightly-gpu
    env:
      PYTHONPATH: /home/jr/aws_spot
    volumeMounts:
      - name: aws-vol
        mountPath: /home/jr/aws_spot    # a directory inside the container where the "project" volume should be mounted

instances:
  - name: i2
    provider: aws
    parameters:
      region: us-east-2
      instanceType: p2.xlarge
      volumes:
        - name: aws-vol
          parameters:
            size: 5
            deletionPolicy: retain
scripts:
  python: |
    python analyze_sf.py`

and get On-Demand Instance

+-------------------+---------------------+
| Instance State    | running             |
+-------------------+---------------------+
| Instance Type     | p2.xlarge           |
+-------------------+---------------------+
| Availability Zone | us-east-2c          |
+-------------------+---------------------+
| Public IP Address | 3.134.103.146       |
+-------------------+---------------------+
| Purchasing Option | On-Demand Instance  |
+-------------------+---------------------+
| Instance Price    | $0.9000 (us-east-1) |
+-------------------+---------------------+

where mistake?

**Comment by apls777** [comment]
Set the `spotInstance` parameter to "true" in the instance configuration: https://spotty.cloud/docs/providers/aws/instance-parameters.html.

**Comment by PapoKarlo** [comment]
thanks.

and how to terminate instance then script finish?

**Comment by apls777** [comment]
Use the `spotty stop` command.

**Comment by PapoKarlo** [comment]
thanks
